<a href="https://colab.research.google.com/github/25pa1a45a0-cmyk/NASSCOM/blob/main/NASSCOM_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.array([1,2,3,4,4,5,6])
print(a)
print(a.dtype)
print(a.shape)
print(a.ndim)

[1 2 3 4 4 5 6]
int64
(7,)
1


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.shape)
print(b.ndim)
print(type(b))
print(b)
c=np.array([[[1,2,3]]])
print(c.shape)


(3, 3)
2
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(1, 1, 3)


In [ ]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[4]=56
print(a)
print(x)

[ 1  2  3  4 56]
[1 2 3 4 5]


In [ ]:
b=np.array([12,4,56,68])
y=b.view()
b[3]=12
print(b)
print(y)

[12  4 56 12]
[12  4 56 12]


In [ ]:
key=np.array([[1,5],[2,4]])
element=np.array([3,4])
result=np.linalg.solve(key,element)
print(result)

[1.33333333 0.33333333]


In [ ]:
x=np.zeros((2,2))
y=np.ones((3,4))
z=np.arange(1,5,1)
print(x)
print(y)
print(z)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 2 3 4]
