<a href="https://colab.research.google.com/github/25pa1a45a0-cmyk/NASSCOM/blob/main/NumPy_Practice_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Exercises

Solve each question in the code cell below it. Do not just re-run the lab examples — use **different numbers/data** than what was shown in class so you are actually writing the logic yourself.

Run each cell with **Shift + Enter** and check that your output makes sense before moving to the next question.

### Q1. Creating a 1-D array
Create a 1-D NumPy array containing 6 numbers of your choice. Print the array and print its type using `type()`.

In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print(type(a))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


### Q2. Creating a 2-D array
Create a 2-D NumPy array with 3 rows and 2 columns (any numbers). Print the array.

In [6]:
b=np.array([[1,2],[3,4],[2,2]])
print(b)


[[1 2]
 [3 4]
 [2 2]]


### Q3. Creating a 3-D array
Create a 3-D NumPy array made up of two 2x3 matrices (2 blocks, each with 2 rows and 3 columns). Print the array.

In [2]:
import numpy as np
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(c)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


### Q4. Checking the number of dimensions
Using the three arrays you created in Q1, Q2, and Q3, print the number of dimensions of each using the `.ndim` attribute.

In [7]:
print(a.ndim)
print(b.ndim)
print(c.ndim)


1
2
3


### Q5. Accessing elements with indexing
Create a 2-D array with 2 rows and 5 columns of your own numbers.
1. Print the 3rd element of the 1st row using positive indexing.
2. Print the last element of the 2nd row using **negative** indexing.

In [9]:
d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(d[0,2])
print(d[1,-1])


3
10


### Q6. Accessing elements in a 3-D array
Using the 3-D array you created in Q3, access and print one specific element using three indices, e.g. `arr[block, row, col]`.

In [10]:
print(c[1,0,1])


8


### Q7. Checking data type
Create one NumPy array of integers and one NumPy array that contains at least one decimal number. Print the `.dtype` of each and explain in a comment why they are different.

In [11]:
i=np.array([1,2,3,4,5])
j=np.array([1,2.2,3,4,5])
print(i.dtype)
print(j.dtype)

int64
float64


They are different because numpy creates an array which stores same data type elements As numpy refers to numerical python which may be either int or float.If there is atleast one element in float remainaing elements are considered as float.

### Q8. Copy vs View
Create a 1-D array. Make a **copy** of it using `.copy()` and a **view** of it using `.view()`. Change the first element of the original array, then print the original array, the copy, and the view. In a comment, explain what you observe and why.

In [12]:
k=np.array([12,14,35,46,72])
l=k.copy()
m=k.view()
k[0]=100
print(k)
print(l)
print(m)


[100  14  35  46  72]
[12 14 35 46 72]
[100  14  35  46  72]


This copy()  does not reflect changes in original array where as view() reflects the changes in original array

### Q9. Shape of an array
1. Create a 2-D array with 3 rows and 4 columns and print its `.shape`.
2. Create a 1-D array of 4 numbers with `ndmin=5` and print both the array and its shape.

In [14]:
p=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10]])
print(p.shape)
q=np.array([1,2,3,4],ndmin=5)
print(q)
print(q.shape)


(4, 4)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


### Q10. Reshaping arrays
Create a 1-D array with 15 elements. Reshape it into a 2-D array with 3 rows and 5 columns using `.reshape()`. Print the result.

In [16]:
l=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(l.reshape(3,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Q11. Linear algebra with NumPy
Solve the following system of equations using `np.linalg.solve()`:

2x + y = 11

x + 3y = 18

Print the values of x and y.

In [19]:
L=np.array([[2,1],[1,3]])
M=np.array([11,18])
res=np.linalg.solve(L,M)
print(res)


[3. 5.]


### Q12. arange, zeros, and ones
1. Use `np.zeros()` to create a 4x2 array of zeros.
2. Use `np.ones()` to create a 3x3 array of ones.
3. Use `np.arange()` to create an array of numbers from 5 to 30 with a step of 5.

Print all three.

In [20]:
A=np.zeros((4,2))
B=np.ones((3,3))
C=np.arange(5,30,5)
print(A)
print(B)
print(C)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25]


### Q13. Why NumPy is faster than plain Python
Create two Python lists of 500,000 numbers each. Time how long it takes to add them element-by-element using a Python loop (or list comprehension). Then convert both lists to NumPy arrays and time how long it takes to add them using `+`. Print both times and, in a comment, state which was faster and roughly by how much.

In [24]:
import numpy as np
import time
n=500000
a=list(range(n))
b=list(range(n))
start=time.time()
c=[a[i]+b[i] for i in range(n)]
print(round(time.time()-start,4),"is the python loop time")
p=np.array(a)
q=np.array(b)
result=p[i]+q[i]
print(round(time.time()-start,4),"is the numpy time")


0.0676 is the python loop time
0.1229 is the numpy time


As numpy takes less time for accessing or retrieving any data where as list in python takes more time for retrieving the large data.

### Q14. Vectors vs matrices
Create a 1-D NumPy array representing a single customer's features: `[height_cm, weight_kg, age]` (make up your own values). Then create a 2-D NumPy array representing 4 different customers with the same 3 features each. Print the `.shape` and `.ndim` of both arrays.

In [26]:
customer=np.array([155,49,19])
customers=np.array([[25,30000,70],[25,30000,70],[25,30000,70],[25,30000,70]])
print(customer.shape)
print(customer.ndim)
print(customers.shape)
print(customers.ndim)



(3,)
1
(4, 3)
2


### Q15. Indexing and slicing to build X and y
Create a 2-D array with 6 rows and 3 columns, where the last column is a target label (0 or 1) and the first two columns are features (make up your own numbers).
1. Print the first 3 rows only.
2. Print only the first column, for all rows.
3. Split the array into `X` (all columns except the last) and `y` (only the last column), and print both.

In [31]:
import numpy as np
y=np.array([[12,13,14],[23,24,25],[56,64,35],[45,56,67],[69,78,89],[43,32,27]])
print(y[:3])
print(y[:,0])
X=y[:,:-1]
Y=y[:,-1]
print(X)
print(Y)


[[12 13 14]
 [23 24 25]
 [56 64 35]]
[12 23 56 45 69 43]
[[12 13]
 [23 24]
 [56 64]
 [45 56]
 [69 78]
 [43 32]]
[14 25 35 67 89 27]


### Q16. Vectorized operations and boolean masking
Create a 1-D NumPy array of 8 exam scores (0-100) of your choice. Without using any loop:
1. Add 5 bonus marks to every score and print the result.
2. Print a boolean array showing which scores are 50 or above.
3. Print only the scores that are 50 or above using boolean masking.

In [32]:
Scores=np.array([56,45,78,69,89,80,60,90])
print("Adding bonus marks:",Scores+5)
print("Scores that are 50 or above:",Scores>=50)
print("Scores that are 50 or above:",Scores[Scores>=50])


Adding bonus marks: [61 50 83 74 94 85 65 95]
Scores that are 50 or above: [ True False  True  True  True  True  True  True]
Scores that are 50 or above: [56 78 69 89 80 60 90]
